### ISSUE TITLE
請問 Script 用法?

### ISSUE THREAD

**Issue by ghost** [seagoat/pillars_of_eternity_Chinese#1]
你好，目前我想重新漢化，但是碰到省略號的問題，請問要如何使用你的 Script ?
我的作法如下:
1. 先下載你的 excel 檔案
2. 修改 excel 中的翻譯
3. 使用官方工具 Loc Builder 產生出 stringtable 檔案
但是產生出來的 stringtable 會出現省略號以及 missing character
要如何使用你的 Script 才可以正常? 謝謝

**Comment by seagoat** [comment]
1. 省略号的处理方法是每个汉字前后加空格
2. excel 是官方提供的。我自己测试过基本没用。 因为版本更新之后，缺少很多文字，因此出现了 missing xxx 的问题

目前我的策略是：
1. 从你自己本地的游戏中把文本文件 copy 出来，做为基础
这些文件都是stringtable 文件，其实是文本文件
2. 直接编辑中间的文字记好了
你可以考虑使用这些文件

我的脚本是 python 写的，比较乱。
不知道你有 python 基础么

**Comment by JasonChiuCC** [comment]
我想知道你最後的 Mod 是怎麼產生出來的
我會 python 只是不知道你使用的順序是什麼
不過如果你沒使用excel 那為什麼裡面已經翻譯過了

**Comment by seagoat** [comment]
最后我只用了 update_string_table.py 这一个脚本
1. 我收集汇总了多个翻译组的结果
2. 我是用自己当前版本的官方 string table， 使用 id 做索引，在翻译组的结果里面查找替换
   2.1 如果找不到，就保留原始英文
3. 最后输出的时候在每个汉字前后加空格

**Comment by JasonChiuCC** [comment]
喔，了解，所以 string table 中的 id 都是唯一的就是了
我以為你是以 excel 為基準，然後轉為  string table 後
才用翻譯組的結果裡面查找替換，找不到就插入原始英文
我想以  excel 為基準是因為他有英文對照
如果直接使用 string table 為基準修改的話會不知道他原本他對應的英文是什麼

**Comment by seagoat** [comment]
原始的 string table 中，包含原始的英文的。
你打开看看就知道了

excel 的版本太老了。跟我这边手头的哪个版本都不匹配...
