### ISSUE TITLE
地名翻译出现矛盾

### ISSUE THREAD

**Issue by haphap** [seagoat/pillars_of_eternity_Chinese#4]
如：
1. 努亚堡与赛德努亚
2. 铜板巷与铜径
3. 昂德拉赠礼与昂德拉之地

**Comment by seagoat** [comment]
目前因为是多个翻译组合并的.
而且优先以 trow 的为主.
trow 没有翻译完整,所以不可避免的出现地名不符合的情况

如果需要一致的翻译,需要限定某一个翻译组的结果就好了
